name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir -p out/modules
        cp modules/pyfuck.py out/modules/
        cp index.html out/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'